-- public.personas definition

-- Drop table

-- DROP TABLE public.personas;

CREATE TABLE public.personas (
	persona_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(255) NOT NULL,
	edad int4 NULL,
	genero varchar(255) NULL,
	identificacion varchar(255) NOT NULL,
	nombre varchar(255) NOT NULL,
	telefono varchar(255) NOT NULL,
	CONSTRAINT personas_edad_check CHECK (((edad <= 200) AND (edad >= 18))),
	CONSTRAINT personas_pkey PRIMARY KEY (persona_id)
);


-- public.clientes definition

-- Drop table

-- DROP TABLE public.clientes;

CREATE TABLE public.clientes (
	cliente_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	contrasenia varchar(255) NOT NULL,
	estado bool NULL,
	persona_id int8 NULL,
	CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id),
	CONSTRAINT fkqqdwv2x70kik01nxcgkxvh8ue FOREIGN KEY (persona_id) REFERENCES public.personas(persona_id)
);